-- LA2TA — in-app notifications for signed-in users.
-- Current notification type: favorite offer nearing expiry.

create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_key text not null,
  type text not null check (type in ('favorite_expiring')),
  offer_id integer references public.offers(id) on delete cascade,
  title text not null,
  body text not null,
  href text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  unique (user_id, notification_key)
);

create index if not exists user_notifications_user_created_idx
  on public.user_notifications(user_id, created_at desc);

create index if not exists user_notifications_user_unread_idx
  on public.user_notifications(user_id, read_at)
  where read_at is null;

alter table public.user_notifications enable row level security;

drop policy if exists user_notifications_select_own on public.user_notifications;
drop policy if exists user_notifications_update_own on public.user_notifications;

create policy user_notifications_select_own
  on public.user_notifications
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy user_notifications_update_own
  on public.user_notifications
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
