-- LA2TA production schema for Supabase Postgres.
-- No demo rows are inserted here: production starts clean and is populated from the admin panel.

create table if not exists public.stores (
  id integer generated by default as identity primary key,
  name text not null,
  description text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  address text not null default '',
  latitude double precision,
  longitude double precision,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.offers (
  id integer generated by default as identity primary key,
  store_id integer not null references public.stores(id) on delete cascade,
  category_id integer references public.categories(id) on delete set null,
  title text not null,
  description text not null default '',
  image_url text not null default '',
  old_price double precision,
  new_price double precision,
  discount_percentage integer,
  offer_type text not null default 'discount',
  start_at timestamptz not null,
  end_at timestamptz not null,
  is_featured boolean not null default false,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','DRAFT','PAUSED','EXPIRED')),
  impressions integer not null default 0,
  views integer not null default 0,
  map_clicks integer not null default 0,
  call_clicks integer not null default 0,
  whatsapp_clicks integer not null default 0,
  shares integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint offers_date_order check (end_at > start_at),
  constraint offers_discount_range check (discount_percentage is null or discount_percentage between 0 and 100)
);

create index if not exists offers_status_end_at_idx on public.offers(status, end_at);
create index if not exists offers_category_id_idx on public.offers(category_id);
create index if not exists offers_store_id_idx on public.offers(store_id);
create index if not exists offers_start_end_idx on public.offers(start_at, end_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists stores_set_updated_at on public.stores;
create trigger stores_set_updated_at
before update on public.stores
for each row execute function public.set_updated_at();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists offers_set_updated_at on public.offers;
create trigger offers_set_updated_at
before update on public.offers
for each row execute function public.set_updated_at();

alter table public.stores enable row level security;
alter table public.categories enable row level security;
alter table public.offers enable row level security;

-- API access is intentionally server-only through SUPABASE_SECRET_KEY.
-- No anon/authenticated table policies are created.

insert into storage.buckets (id, name, public)
values ('offer-images', 'offer-images', true)
on conflict (id) do update set public = true;
